// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnkrulbjoejcansqwanm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indua3J1bGJqb2VqY2Fuc3F3YW5tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUyNzYyNTUsImV4cCI6MjA1MDg1MjI1NX0.ANRDZnuJwoX10GoHJspG0alnlKlZ5rMCUW3XWPfjlfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);